version: '3'

services:
  database:
    image: circleci/postgres:alpine-ram
    ports:
      - 5432:5432
    env_file:
      - .db.env
  pgadmin:
    # use hostname host.docker.internal to connect instead of localhost
    # and use db user "knex"
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    restart: unless-stopped
