Link:
  type: object
  properties:
    creatorId:
      type: string
    hash:
      type: string
      minLength: 4
      maxLength: 25
    originalUrl:
      type: string
      # maxLength: 100
    shortenedUrl:
      type: string
      readOnly: true
    brandedUrl:
      type: string
      readOnly: true
    meta:
      type: object
      properties:
        author:
          type: string
          # maxLength: 100
        date:
          type: string
          format: date
        description:
          type: string
          # maxLength: 100
        lang:
          type: string
          # maxLength: 10
        logo:
          type: string
          format: uri
          maxLength: 100
        publisher:
          type: string
          # maxLength: 100
        title:
          type: string
          # maxLength: 100
      additionalProperties: false
  required:
    - creatorId
    - originalUrl
  additionalProperties: false
